updated link
PrismarineJS/flying-squid pull request #466
Opened 2021-01-19 18:24 UTC by u9g

because of this https://github.com/PrismarineJS/flying-squid/issues/465

2021-01-19 22:33 UTC, wvffle approved these changes

2021-01-23 16:47 UTC, rom1504 requested changes

2021-01-23 16:47 UTC, rom1504 commented on docs/README.md
> +Or try our autoupdating flying-squid server [autonomous-squid](https://github.com/eman3/autonomous-squid)
Is this a random fork ?
Who is eman3 ?

2021-01-24 03:13 UTC, u9g commented
I guess so

2021-01-24 03:13 UTC, closed without merging