Moved player health, food, and stamina updates to player.js
PrismarineJS/flying-squid pull request #486
Opened 2021-02-28 13:49 UTC by TheDudeFromCI

There currently was no way to update food or foodStamina, and having health packets in the pvp.js file didn't make much sense.

2021-02-28 16:36 UTC, rom1504 requested changes
Player is a type a plugin in flying-squid.
If we create a player plugin then it will contain all plugins

2021-02-28 16:36 UTC, rom1504 commented
Maybe health.js ?

2021-03-01 00:04 UTC, TheDudeFromCI commented
> Maybe health.js ?

Done.

2021-03-01 01:16 UTC, rom1504 commented on src/lib/plugins/health.js
> +  player.updateFood = (food) => {
can you add that to the doc ?

2021-03-03 12:41 UTC, rom1504 approved these changes

2021-03-03 12:41 UTC, rom1504 commented
Ah ci is failing

2021-03-03 12:56 UTC, TheDudeFromCI commented
> Ah ci is failing

Looks like it's failing for an unrelated reason.
```
March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for redstone_torch
Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for repeater
Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for oak_sign
Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for spruce_sign
Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for birch_sign
Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for acacia_sign
Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for jungle_sign
Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for dark_oak_sign
```

2021-03-03 14:10 UTC, Karang commented
> > Ah ci is failing
> 
> Looks like it's failing for an unrelated reason.
> 
> ```
> March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for redstone_torch
> Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for repeater
> Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for oak_sign
> Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for spruce_sign
> Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for birch_sign
> Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for acacia_sign
> Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for jungle_sign
> Warning: G      March 3rd 2021, 12:16:18 [Warning] onItemPlace handler was registered twice for dark_oak_sign
> ```

those warnings cannot make ci fail

2021-03-03 14:14 UTC, TheDudeFromCI commented
Just checked, the CI was not failing, apparently.
@rom1504 @Karang 

![Screenshot from 2021-03-03 07-13-30](https://user-images.githubusercontent.com/3118172/109818218-fbfd1700-7bef-11eb-856f-c27e07b4a415.png)

![Screenshot from 2021-03-03 07-12-39](https://user-images.githubusercontent.com/3118172/109818106-dd971b80-7bef-11eb-91ad-f8c17e52822c.png)

2021-03-04 22:09 UTC, rom1504 approved these changes

2021-03-04 22:09 UTC, merged