[/tp command] - Check if x/y/z is valid
PrismarineJS/flying-squid pull request #576
Opened 2022-03-14 19:23 UTC by andriycraft

2022-03-14 20:32 UTC, darksunlight requested changes

2022-03-14 20:32 UTC, darksunlight commented on src/lib/plugins/tp.js
> +        if (x > 29999999 || y > 4096 || y < -4096 || z > 29999999) {
What about negative x and z coordinates? You can check for the absolute values of x y and z instead.

2022-03-20 18:36 UTC, MokiyCodes commented on src/lib/plugins/tp.js
> +        if (x > 29999999 || y > 4096 || y < -4096 || z > 29999999 || z < -29999999 || x < -29999999) {
using `Math.abs(x) > 29999999 || Math.abs(y) > 4096 || Math.abs(z) > 29999999` would likely look nicer

2022-03-20 18:38 UTC, MokiyCodes requested changes
using `Math.abs(x) > 29999999 || Math.abs(y) > 4096 || Math.abs(z) > 29999999` would likely look nicer

2022-03-20 20:47 UTC, andriycraft commented
> using `Math.abs(x) > 29999999 || Math.abs(y) > 4096 || Math.abs(z) > 29999999` would likely look nicer

Remember that we also have for negative x/y/z
so your code will look like this
`Math.abs(x) > 29999999 || Math.abs(y) > 4096 || Math.abs(z) > 29999999 || Math.abs(x) < -29999999 || Math.abs(y) < -4096 || Math.abs(z) < -29999999`

so I think my code is nicer

2022-03-20 20:52 UTC, andriy332 approved these changes

2022-03-20 20:53 UTC, darksunlight commented
> > using `Math.abs(x) > 29999999 || Math.abs(y) > 4096 || Math.abs(z) > 29999999` would likely look nicer
> 
> Remember that we also must have check for negative x/y/z so your code will look like this `Math.abs(x) > 29999999 || Math.abs(y) > 4096 || Math.abs(z) > 29999999 || Math.abs(x) < -29999999 || Math.abs(y) < -4096 || Math.abs(z) < -29999999`
> 
> so I think my code is nicer

No. Not really. Math.abs returns the absolute value of its first parameter. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs

2022-03-21 09:32 UTC, MokiyCodes approved these changes
lgtm

2022-03-27 18:40 UTC, merged